name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install cross-env
        run: npm install --save-dev cross-env

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: cd
        run: cd site

      - name: build
        run: npm run build

      - name: create CNAME
        run: echo "$domain" > dist/CNAME
        env:
          domain: ${{ secrets.DOMAIN }}

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
